# Kombinierte Beispielkonfiguration für ESPHome-Firmware zur gleichzeitigen
# Messung von Stromverbrauch (Ferraris-Zähler) und Wasserverbrauch (Pulszähler)

# Allgemeine Konfiguration (anzupassen)
esphome:
  name: energy-water-meter
  friendly_name: Strom- und Wasserzähler
  project:
    name: custom.energy_water_meter
    version: 1.0.0

# Beispiel ESP8266 Firmware (kann durch entsprechende Konfiguration ersetzt werden)
esp8266:
  board: esp01_1m

# Ferraris-Komponente einbinden (erforderlich für Stromzähler)
external_components:
  - source: github://jensrossbach/esphome-ferraris-meter@v1.5.1
    components: [ferraris]

# Logging aktivieren (optional)
logger:
  level: INFO

# Home Assistant API aktivieren (erforderlich bei Verwendung mit Home Assistant)
api:
  encryption:
    key: !secret ha_api_key

# Over-the-Air Updates aktivieren (empfohlen)
ota:
  - platform: esphome
    password: !secret ota_password

# Wi-Fi aktivieren (erforderlich)
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Fallback Hotspot (Captive Portal) aktivieren
  ap:
    ssid: Meter Fallback Hotspot
    password: !secret fallback_hs_password

# Benötigt für Fallback Hotspot
captive_portal:

# Ferraris-Komponente für Stromzähler (erforderlich)
ferraris:
  id: ferraris_meter
  analog_input: adc_input
  analog_threshold: adc_threshold
  energy_start_value: last_energy_value

# Globale Variablen für Wasserzähler
globals:
  # Zählerstand in Litern (intern ganzzahlig)
  - id: water_volume_total_liters
    type: int64_t
    restore_value: no
    initial_value: '0'
  # Letzte Zeit für Durchflussberechnung
  - id: last_pulse_time
    type: unsigned long
    restore_value: no
    initial_value: '0'

# Binäre Sensoren
binary_sensor:
  # === STROMZÄHLER (Ferraris) ===
  - platform: ferraris
    # Diagnostischer Sensor für erkannte Umdrehungen während Kalibrierung
    rotation_indicator:
      name: Strom Umdrehungsindikator
    # Diagnostischer Sensor für Status der automatischen analogen Kalibrierung
    analog_calibration_state:
      name: Strom Status Analoge Kalibrierung
    # Diagnostischer Sensor für Ergebnis der automatischen analogen Kalibrierung
    analog_calibration_result:
      name: Strom Ergebnis Analoge Kalibrierung
  
  # === WASSERZÄHLER (Puls) ===
  # Wasserzähler Puls-Sensor
  - platform: gpio
    id: water_pulse
    pin:
      number: GPIO5  # GPIO-Pin für Wasserzähler (unterschiedlich vom Stromzähler!)
      mode:
        input: true
        pullup: true
    filters:
      # Entprellung
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_press:
      then:
        # Bei jedem Puls wird der Zählerstand um 10 Liter erhöht
        - lambda: |-
            // Aktuellen Zählerstand um 10 Liter erhöhen (ganzzahlig)
            id(water_volume_total_liters) += 10;
            
            // Zeitstempel für Durchflussberechnung
            unsigned long current_time = millis();
            unsigned long time_diff = current_time - id(last_pulse_time);
            
            // Durchfluss berechnen (nur wenn vorheriger Puls vorhanden)
            if (id(last_pulse_time) > 0 && time_diff > 0) {
              // 10 Liter pro Puls, time_diff in ms -> m³/h
              // Ganzzahlig: (10 * 3600000) / time_diff / 1000 = 36000 / time_diff
              float flow_rate = 36000.0f / time_diff;
              id(water_flow).publish_state(flow_rate);
            }
            
            id(last_pulse_time) = current_time;
            
            // Zählerstand aktualisieren (Umwandlung Liter -> m³)
            float volume_m3 = id(water_volume_total_liters) / 1000.0f;
            id(water_meter).publish_state(volume_m3);
            
            ESP_LOGD("water_meter", "Puls erkannt - Zählerstand: %lld L (%.3f m³)", id(water_volume_total_liters), volume_m3);
  
  # Diagnostischer Sensor für WLAN-Verbindungsstatus
  - platform: status
    name: Status

# Numerische Sensoren
sensor:
  # === STROMZÄHLER (Ferraris) ===
  - platform: ferraris
    # Sensor für aktuellen Stromverbrauch
    power_consumption:
      name: Stromverbrauch Momentan
    # Sensor für Stromzählerstand
    energy_meter:
      name: Stromzählerstand
      unit_of_measurement: kWh
      accuracy_decimals: 2
      filters:
        - multiply: 0.001
    # Diagnostischer Sensor für analoge Bandbreite während letzter Kalibrierung
    analog_value_spectrum:
      name: Strom Analoge Bandbreite
  
  # Sensor für analogen Eingang des Stromzählers
  - platform: adc
    id: adc_input
    pin: GPIO17  # ADC-Pin des ESP8266
    internal: true
    raw: true
    samples: 10
    update_interval: 50ms
  
  # === WASSERZÄHLER (Puls) ===
  # Sensor für momentanen Wasserdurchfluss (Kubikmeter pro Stunde)
  - platform: template
    id: water_flow
    name: Wasserdurchfluss
    icon: mdi:water-pump
    unit_of_measurement: "m³/h"
    accuracy_decimals: 2
    state_class: measurement
    device_class: volume_flow_rate
    # Nach 5 Minuten ohne Puls -> Durchfluss auf 0 setzen
    filters:
      - timeout: 300s
        value: 0.0
  
  # Sensor für Gesamtwasserverbrauch (Zählerstand)
  - platform: template
    id: water_meter
    name: Wasserzählerstand
    icon: mdi:counter
    unit_of_measurement: "m³"
    accuracy_decimals: 3
    state_class: total_increasing
    device_class: water
  
  # === ALLGEMEINE SENSOREN ===
  # Sensor für Wi-Fi Signalstärke
  - platform: wifi_signal
    name: Wi-Fi Signal
    update_interval: 60s

# Text Sensoren
text_sensor:
  - platform: wifi_info
    # Diagnostischer Sensor für IP-Adresse des ESP-Mikrocontrollers
    ip_address:
      name: IP Adresse

# Zahlen-Komponenten
number:
  # === STROMZÄHLER (Ferraris) ===
  # Importiere letzten Stromzählerstand aus Home Assistant
  - platform: homeassistant
    id: last_energy_value
    entity_id: input_number.stromzaehler_letzter_wert
  
  # Zahl für ADC-Schwellwert des Stromzählers
  - platform: template
    id: adc_threshold
    name: Strom ADC Schwellwert
    icon: mdi:speedometer-slow
    entity_category: config
    mode: box
    optimistic: true
    initial_value: 50
    min_value: 0
    max_value: 1000
    step: 1
  
  # Zahl für manuelles Überschreiben des Stromzählerstands
  - platform: template
    id: target_energy_value
    name: Strom Manueller Zählerstand
    icon: mdi:counter
    unit_of_measurement: kWh
    device_class: energy
    entity_category: config
    mode: box
    optimistic: true
    min_value: 0
    max_value: 1000000
    step: 0.01
  
  # === WASSERZÄHLER (Puls) ===
  # Importiere letzten Wasserzählerstand aus Home Assistant
  - platform: homeassistant
    id: last_water_value
    entity_id: input_number.wasserzaehler_letzter_wert
    on_value:
      then:
        - lambda: |-
            // Beim Start den gespeicherten Wert aus Home Assistant laden (m³ -> Liter)
            if (x >= 0) {
              id(water_volume_total_liters) = (int64_t)(x * 1000.0f);
              id(water_meter).publish_state(x);
              ESP_LOGI("water_meter", "Zählerstand wiederhergestellt: %lld L (%.3f m³)", id(water_volume_total_liters), x);
            }
  
  # Zahl für manuelles Überschreiben des Wasserzählerstands
  - platform: template
    id: target_water_value
    name: Wasser Manueller Zählerstand
    icon: mdi:counter
    unit_of_measurement: m³
    device_class: water
    entity_category: config
    mode: box
    optimistic: true
    min_value: 0
    max_value: 10000
    step: 0.01

# Switch-Komponenten
switch:
  # === STROMZÄHLER (Ferraris) ===
  - platform: ferraris
    # Diagnostischer Schalter für Aktivierung/Deaktivierung des Kalibrierungsmodus
    calibration_mode:
      name: Strom Kalibrierungsmodus

# Button-Komponenten
button:
  # === STROMZÄHLER (Ferraris) ===
  # Button zum manuellen Überschreiben des Stromzählerstands
  - platform: template
    name: Stromzählerstand überschreiben
    icon: mdi:download
    entity_category: config
    on_press:
      - ferraris.set_energy_meter:
          id: ferraris_meter
          value: !lambda |-
            float val = id(target_energy_value).state;
            return (val >= 0) ? val : 0;
  
  # Diagnostischer Button für automatische Kalibrierung des analogen Signals
  - platform: template
    name: Strom Auto-Kalibrierung starten
    icon: mdi:auto-fix
    entity_category: diagnostic
    on_press:
      - ferraris.start_analog_calibration:
          id: ferraris_meter
          num_captured_values: 6000
          min_level_distance: 6.0
          max_iterations: 3
  
  # === WASSERZÄHLER (Puls) ===
  # Button zum manuellen Überschreiben des Wasserzählerstands
  - platform: template
    name: Wasserzählerstand überschreiben
    icon: mdi:download
    entity_category: config
    on_press:
      - lambda: |-
          float val = id(target_water_value).state;
          if (val >= 0) {
            id(water_volume_total_liters) = (int64_t)(val * 1000.0f);
            id(water_meter).publish_state(val);
            id(last_pulse_time) = 0;
            ESP_LOGI("water_meter", "Zählerstand manuell gesetzt: %lld L (%.3f m³)", id(water_volume_total_liters), val);
          }
